name: Deployment

on:
  push:
    branches:
      - deepan

jobs:
  deploy_to_development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Development
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to development branch"
         
  deploy_to_deepan:
    runs-on: ubuntu-latest
    needs: [deploy_to_development]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


   
