name: Deployment

on:
  push:
    branches:
      - production

jobs:

  deploy_to_development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Development
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to development branch"
         
  
     


   
